### ISSUE TITLE
What would be the benign gNB set up

### ISSUE THREAD

**Issue by qiqingh** [asset-group/5ghoul-5g-nr-attacks#22]
Hello, after reviewing the demo video, I observed that the COT UE initially connects with the benign gNB. Subsequently, the 5GHOUL infiltrates and initiates the attack.

Could you please provide more details on how the benign gNB is configured in these demos?

**Comment by Matheus-Garbelini** [comment]
For the benign base station, the configuration is the same as the attacker, with the exception that fuzzing and timeout are disabled: `--GlobalTimeout=false --EnableMutation=false`.
The full command is also described in the final code line of the quick start section: https://github.com/asset-group/5ghoul-5g-nr-attacks?tab=readme-ov-file#2--quick-start-docker-container

Furthermore, we run the rogue 5G base station and benign 5G base station in separate computers to avoid performance issues. However, benign 5G and 4G can run on the same computer.

* **Config for 5G:** Since 5Ghoul uses OpenAirInterface, the specific configuration file that the gNB stack uses (band n78) is this one: https://github.com/asset-group/5ghoul-5g-nr-attacks/blob/master/configs/5gnr_gnb/n78.106.conf. It's the same one in [OAI official repo](https://gitlab.eurecom.fr/oai/openairinterface5g/-/blob/develop/targets/PROJECTS/GENERIC-NR-5GC/CONF/gnb.sa.band78.fr1.106PRB.usrpb210.conf?ref_type=heads), but with MCC, MNC, and amf_ip_address changed to work with Open5GS core network.
You can also increase the transmission attenuation (parameter att_tx) of the benign base station to "simulate" a benign gNB that is more distant to the phone than the malicious base station: https://github.com/asset-group/5ghoul-5g-nr-attacks/blob/master/configs/5gnr_gnb/n78.106.conf#L228. Any value from 18 to 22 should be enough.
Similarly, you can decrease the transmission attenuation of the malicious gNB to increase its transmission power so the hijacking (e.g., after toggling airplane mode) is easier.
Finally, since we use Open5GS software for the core network, this config file is used for it: https://github.com/asset-group/5ghoul-5g-nr-attacks/blob/master/configs/5gnr_gnb/open5gs.yaml

* **Config for 4G:** We use OpenAirInterface again, but the lte-softmodem binary, which runs a 4G base station (eNB). For that, you'd have to compile from scratch following OAI documentation: https://gitlab.eurecom.fr/oai/openairinterface5g/-/wikis/HowToConnectCOTSUEwithOAIeNBNew
Configuration for OAI 4G is provided in this email for your convinience (enb.band7.tm1.50PRB.usrpb210.conf). It uses the same core network settings as 5G since Open5GS works as AMF or MME.
Similarly to 5G, the config. settings for OAI 4G was taken from the OAI repo: https://gitlab.eurecom.fr/oai/openairinterface5g/-/blob/develop/ci-scripts/conf_files/enb.band7.tm1.50prb.usrpb210.conf?ref_type=heads, but with MCC, MNC, and amf_ip_address changed to work with Open5GS core network.

**Comment by qiqingh** [comment]
@Matheus-Garbelini Thanks for your detailed reply!

I have an additional inquiry regarding the benign LTE setup, specifically pertaining to the OAI 4G. Could you please inform me which branch you utilized for building? I attempted to build from the current branch, but unfortunately, encountered failures in building eNB.

Furthermore, upon reviewing your demonstration video (https://www.youtube.com/watch?v=84DDy_4ofxwo), I noticed that the benign LTE setup appears to employ srsRAN. Could you confirm if this is the case?

Thank you for your attention to this matter.

**Comment by Matheus-Garbelini** [comment]
> I have an additional inquiry regarding the benign LTE setup, specifically pertaining to the OAI 4G. Could you please inform me which branch you utilized for building? I attempted to build from the current branch, but unfortunately, encountered failures in building eNB.

Hi @qiqingh, note that the current branch of OAI in this repo is built using Ubuntu 18.04, which might not be compatible with latest Ubuntu (20.04, 22.04, etc). You can perhaps try with [latest OAI development branch](https://gitlab.eurecom.fr/oai/openairinterface5g) which should support latest OS.

> Furthermore, upon reviewing your demonstration video (https://www.youtube.com/watch?v=84DDy_4ofxwo), I noticed that the benign LTE setup appears to employ srsRAN. Could you confirm if this is the case?

Yes, at the time, we were using latest srsran. We decided to use a single code base (OAI) after that. But if you want to try with srsran, you can use this config file (band 7): [enb.txt](https://github.com/asset-group/5ghoul-5g-nr-attacks/files/14353215/enb.txt)
This file is taken from the [default config file provided by srsran](https://github.com/srsran/srsRAN_4G/blob/master/srsenb/enb.conf.example), with a change in the mme_addr to match open5gs.

**Comment by qiqingh** [comment]
Got it, thanks for your illustration!
